### ISSUE TITLE
Split minitwitt.go into multiple files

### ISSUE THREAD

**Issue by madspdrsen** [matt035343/devops#10]

**Comment by fhoa** [comment]
@matt035343 @madspdrsen @MackatITU @JM-Development 
Tænker at ændre strukturen på projektet her idag. Det her er mit forslag til hvordan det skal se ud. Nogle indvendinger, forslag eller ændringer ?

.gitignore
CONTRIBUTE.md
Makefile
go.mod
go.sum
/src/
---/router.go
---/utils.go
---/flagtool.go
---/viewModels/
--------------/User.go
--------------/Request.go
--------------/Message.go
---/database/
------------/init.go
------------/schema.sql
---/models/
----------/user.go
----------/timeline.go
----------/login.go
---/middleware/
--------------/auth.go

**Comment by madspdrsen** [comment]
Ser umiddelbart fint ud!

Husk at opdatere go-guide.txt hvis der er ændringer i hvordan tingene skal compiles :)

**Comment by matt035343** [comment]
Mangler at flytte routes og middleware i sine egne filer
