### ISSUE TITLE
Check and increase security

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#128]
Examlples:
- Avoid brute force by disallowing more than 3 attempts
- Send confirmation emails
- Avoid XSS
- Multifactor login
- Strong password policy

**Comment by matt035343** [comment]
@MackatITU måske du har ret. Tømte bare lige hovedet. Men det er fint at nævne til eksamen though.

Multi-faktor login burde være mere håndgribelig, da vi ikke skal bruge en mail server, og der eksisterer vist libraries til at klare det

**Comment by MackatITU** [comment]
Jeg kom lige i tanke om, vi skal vel ikke have multifactor login / confirmation mails for så vil simulatoren ikke virke? 
Simulatoren går jo ikke ind og confirmer en email eller laver two-factor auth.

**Comment by matt035343** [comment]
@MackatITU Vi kunne nøjes med at gøre det med brugerdelen. Man ville alligevel aldrig have en ubeskyttet API som simulatordelen er lige nu.

**Comment by JM-Development** [comment]
Hvad med at benytte https ? 
Det sikrer vel egentlig ikke vores webservice, men sikrer at bruger info ikke bliver opsnappet (eller gør det sværere i hvert fald)

**Comment by matt035343** [comment]
@JM-Development Det lyder også som en god idé

**Comment by fhoa** [comment]
Det kan sættes op ved brug af to ekstra containers i docker-compose filen. 
dvs. letsencrypt & Certbot. 
Dette bygger på nginx. Tager dog nok lidt tid at sætte op (1-5 timer)

**Comment by MackatITU** [comment]
Solved in PR #146 
(Without multifactor and email service)
