### ISSUE TITLE
Penetration test

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#130]
OWASP, nmap, og hvad der nu ellers kan bruges.

**Comment by JM-Development** [comment]
Skal jeg skrive en side omkring dette her ? 
eller blot udskrive rapporter fra owasp mm. ?

**Comment by JM-Development** [comment]
btw mankan lave SQL Injection, selvom jeg har lidt svært ved at udnytte det. Må jo ikke lave Delete tables etc ;)

**Comment by matt035343** [comment]
@JM-Development Tror det ville være godt at skrive side om det, hvis muligt. Så kan vi lægge det som bilag i vores rapport.

**Comment by JM-Development** [comment]
@matt035343 All right. Jeg skriver lidt om det :) Jeg kan se at de ikke har rettet deres grafana psw endnu.  Så det kan jeg vel tage med ligesom med brugen af https.

**Comment by matt035343** [comment]
Jeg tænkte nu mere på vores egen services. Jeg ved dog ikke om de er interesserede i Gruppe I's "security report" også?

**Comment by JM-Development** [comment]
oh, okay, vi er så vidt jeg kan se ikke åbne for sql injection. Har scannet vores system, og vi klarer os ganske fint :)

**Comment by matt035343** [comment]
Det lyder super :)
Så jeg tænker (I andre er velkomne til at være uenige), et kort skrevet dokument omkring penetration test af vores egen service, som vi kan lægge som bilag i vores rapport.

Og en kort rapport i stikordsform som vi kan sende til Gruppe I omkring deres service.
