### ISSUE TITLE
Start monitoring group I

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#131]

**Comment by Durix** [comment]
Greetings Group K.
You can find our (Group I) SLA @ 
https://github.com/minitwit-tdb/DevOps/wiki/Minitwit-Service-License-Agreement-(SLA)
Or if you prefer you can download and read the PDF version as well:
[SLAv1.0.pdf](https://github.com/matt035343/devops/files/4388768/SLAv1.0.pdf)
