### ISSUE TITLE
Set up response time and response code graphs in Grafana

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#132]
I already tried to set one up, but I don't think it's showing the right thing...

**Comment by madspdrsen** [comment]
ATM:
Average response time for group i (across network, including latency etc.)
Unsuccessful pings against group i

Average response time for us (server process time, not including latencty ect.)

**Comment by madspdrsen** [comment]
Skal vi bare gå med dem vi har pt? @matt035343

**Comment by matt035343** [comment]
Ja, det bliver vi nok nødt til
