### ISSUE TITLE
Update Dependency diagram

### ISSUE THREAD

**Issue by MackatITU** [matt035343/devops#172]
Efter flere ugers ommøblering rundt omkring i kodebasen bør vi opdatere vores dependency diagram igen.

**Comment by fhoa** [comment]
https://www.draw.io/#G1pceKoFzS-jM_HBGSgGbmXrWr04xS4f_2

**Comment by MackatITU** [comment]
> https://www.draw.io/#G1pceKoFzS-jM_HBGSgGbmXrWr04xS4f_2

Vores gamle diagrammer :)
