### ISSUE TITLE
Test everything in readme

### ISSUE THREAD

**Issue by fhoa** [matt035343/devops#187]

**Comment by JM-Development** [comment]
Noter:
Links til vores minitwit virker ikke. På en måde er de ambigious, selvom det jo skal være der.

Det vil være en god ide at pointere at det er designet til at virke på Ubuntu 18.04, og at vedlejningen er målrettet denne.

example .env  mangler.

postgres
-kan skrive at vi målretter postgres command tool (selvom en bruger jo kan bruge enhver gui, men der kan vi ikke garantere at vores guide virker)

ellers ser det fint ud. Men skal teste igen hvis vi lægger en eksempel .env fil op
