### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by MackatITU** [matt035343/devops#57]

**Comment by fhoa** [comment]
@MackatITU @madspdrsen Får i lavet det sidste step der skal til for at CD er oppe og køre ? Eller har i brug for hjælp?

**Comment by MackatITU** [comment]
Jeg prøver at få det lavet her klokken 13.
- Så må vi se hvordan det går. Jeg regner med det code-snippet du sendte virker nogenlunde fornuftigt ;)

**Comment by fhoa** [comment]
Tjek det her ud. Det er en gut fra DO der nævner et image du kan bruge til ssh
https://www.digitalocean.com/community/questions/how-to-deploy-using-github-action

**Comment by fhoa** [comment]
Det er måske endda bedre at køre SCP efterfulgt at SSH deploy... Hvis vi gør det ved brug af dockerhub, så bliver vores docker-compose fil ikke opdateret ved push til master :/

**Comment by MackatITU** [comment]
Solved in 092a1e3
