### ISSUE TITLE
Use foreign keys and/or join with GORM

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#59]
It works as of now, but the performance can be better as a user is queried per message instead getting all the info in one single query.  I couldn't get foreign keys and/or joins to work with GORM, it should though.

**Comment by matt035343** [comment]
Doesn't seem to work with gorm and sqlit3 together

**Comment by fhoa** [comment]
On hold till/if the database layer is replaced with postgres or mysql

**Comment by fhoa** [comment]
On hold till/if the database layer is replaced with postgres or mysql

**Comment by fhoa** [comment]
Changed to Postgres. This is no longer paused.
