### ISSUE TITLE
Refactor to use Go naming convetion

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#62]

**Comment by MackatITU** [comment]
Kan du beskrive lidt nærmere hvad der menes med GO naming convention? :) 
Altså, give nogle eksempler?

**Comment by matt035343** [comment]
@MackatITU Flere steder i koden bruges snake_case, hvor der burde blive brugt camelCase. Eksempel:
https://github.com/matt035343/devops/blob/dfb135c628e52ca79f03d62c4488edb64fb91ca4/app/src/server/handlers.go#L492

Dette gælder også i konstantnavngivning. Eksempel:
https://github.com/matt035343/devops/blob/dfb135c628e52ca79f03d62c4488edb64fb91ca4/app/src/server/handlers.go#L19

**Comment by matt035343** [comment]
Vi skal også have lavet eksportkommentarer og anden cleanup

**Comment by matt035343** [comment]
@JM-Development hvad er status på denne?

**Comment by JM-Development** [comment]
Den skulle være i mål nu :)
