### ISSUE TITLE
Setup prometheus

### ISSUE THREAD

**Issue by fhoa** [matt035343/devops#77]

**Comment by matt035343** [comment]
@fhoa @MackatITU @madspdrsen @JM-Development 
Hvilke metrics skal vi have?
Jeg tænker noget ala:
- Frekvens af de forskellige endpoints
- Frekvens af de forskellige database kald
- Antallet af brugere, beskeder, osv. (hvis muligt)
- Antallet af de forskellige fejl der kan forekomme
- osv... kom gerne med foreslag

**Comment by fhoa** [comment]
Kun monitor på prod env

**Comment by MackatITU** [comment]
@matt035343 Jeg synes selv du nævner de vigtigste. 
Frekvens af databasekald og genenmsnitlig svartid fra databasen,
Response tid fra server og bruger samt mulig logning af exceptions / fejl?

**Comment by matt035343** [comment]
@MackatITU Jeg tror det med logging af fejl og exceptions kommer om et par uger som et separat emne

**Comment by matt035343** [comment]
Det er sat op med følgende metrics:
- Antal beskeder
- Antal brugere
- Antal følgere
- Antal fjernede følgere
- Antal requests de sidste 5 min
- Antal requests de sidste 15 min
- Antal requests de sidste 60 min
- Histogram over fejlkoder
- Histogram over svartider
