### ISSUE TITLE
Prepare presentation

### ISSUE THREAD

**Issue by matt035343** [matt035343/devops#81]
10 min presentation about:
- architecture
- technologies and programming language
- a view of the monitoring dashboard
- other highlights about out system

**Comment by fhoa** [comment]
https://docs.google.com/presentation/d/13YUeUjQsGblBhEfbgfMNaDSXH-TubamKsHB9-z3wUVM/edit?usp=sharing

**Comment by fhoa** [comment]
Charts:
https://drive.google.com/file/d/1uSIyWSDcIykyQgd_EHKIGqP3aHCzBeV5/view?usp=sharing
