### ISSUE TITLE
Change sqlite3 to postgres

### ISSUE THREAD

**Issue by fhoa** [matt035343/devops#90]

**Comment by matt035343** [comment]
Outline how make the change with least data loss possible. Write a small plan that we can discuss in the report.

**Comment by fhoa** [comment]
Lad os prøve hvad end vi gør på test serveren først. Så kan vi se hvor effektivt det er

**Comment by fhoa** [comment]
Postgres is setup in docker-compose.yaml & app now....

Missing...
- Convert unittests to use postgres (or keep it as sqlite3)
- Conver develop to use postgres
- Convert prod to use postgres
- Convert flagtool to use postgres

**Comment by fhoa** [comment]
https://kirschbaumdevelopment.com/news-articles/using-github-actions-to-setup-ci-cd-with-laravel-and-mysql
To setup postgres in CI so tests can run
